-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY TB_TOP IS
-- Declarations

END TB_TOP;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF TB_TOP IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL reset  : STD_LOGIC;
   SIGNAL clock  : STD_LOGIC;
   SIGNAL PORT_LEDG  : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
   SIGNAL PORT_LEDR  : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
   SIGNAL PORT_HEX0  : STD_LOGIC_VECTOR( 6 DOWNTO 0 );
   SIGNAL PORT_HEX1  : STD_LOGIC_VECTOR( 6 DOWNTO 0 );
   SIGNAL PORT_HEX2  : STD_LOGIC_VECTOR( 6 DOWNTO 0 );
   SIGNAL PORT_HEX3  : STD_LOGIC_VECTOR( 6 DOWNTO 0 );
   SIGNAL PORT_SW    : STD_LOGIC_VECTOR( 7 DOWNTO 0 );
   SIGNAL PORT_KEY   : STD_LOGIC_VECTOR( 2 DOWNTO 0 );
   SIGNAL ena_pc	 : STD_LOGIC;

   


   -- Component Declarations
   COMPONENT TOP
   
  PORT( 	reset, clock						: IN 	STD_LOGIC; 
				PORT_LEDG						: OUT 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_LEDR						: OUT 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_HEX0						: OUT 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX1						: OUT 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX2						: OUT 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX3						: OUT 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_SW							: IN 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_KEY						: IN 	STD_LOGIC_VECTOR(2 downto 0);
				ena_pc							: IN 	STD_LOGIC

				);
		
   END COMPONENT;
   
   COMPONENT TOP_tester
   PORT( 	reset, clock						: OUT 	STD_LOGIC; 
				PORT_LEDG						: IN 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_LEDR						: IN 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_HEX0						: IN 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX1						: IN 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX2						: IN 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_HEX3						: IN 	STD_LOGIC_VECTOR(6 downto 0);
				PORT_SW							: OUT 	STD_LOGIC_VECTOR(7 downto 0);
				PORT_KEY						: OUT 	STD_LOGIC_VECTOR(2 downto 0);
				ena_pc							: OUT 	STD_LOGIC

				);
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : TOP USE ENTITY work.TOP;
   FOR ALL : TOP_tester USE ENTITY work.TOP_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : TOP
   
      PORT MAP (
         reset      => reset,
         clock      => clock,
         PORT_LEDG  => PORT_LEDG,
		 PORT_LEDR  => PORT_LEDR,
         PORT_HEX0  => PORT_HEX0,
         PORT_HEX1  => PORT_HEX1,
         PORT_HEX2  => PORT_HEX2,
         PORT_HEX3  => PORT_HEX3,
         PORT_SW    => PORT_SW,
		 PORT_KEY	=> PORT_KEY,
		 ena_pc		=> ena_pc
         
      );
	  
		
   U_1 : TOP_tester
      PORT MAP (
         reset      => reset,
         clock      => clock,
         PORT_LEDG  => PORT_LEDG,
		 PORT_LEDR  => PORT_LEDR,
         PORT_HEX0  => PORT_HEX0,
         PORT_HEX1  => PORT_HEX1,
         PORT_HEX2  => PORT_HEX2,
         PORT_HEX3  => PORT_HEX3,
         PORT_SW    => PORT_SW,
		 PORT_KEY	=> PORT_KEY,
		 ena_pc		=> ena_pc
      );

END struct;
